Handle login failures #37
sandiegojs/sdjs-speaker-app pull request #38
Opened 2020-07-17 06:55 UTC by rathore-abhay

Handling error response from strapi and displaying it as alert for now.

2020-07-20 22:40 UTC, samanthakem requested changes
Hey there! Thank you for your contribution!

I added a few comments, please ping me if you have questions on why I added those.

2020-07-20 22:40 UTC, samanthakem commented on client/pages/admin/signin.js
> +      .then((jsonResponse) => {
Could you use `catch` instead?

https://medium.com/@lucymarmitchell/using-then-catch-finally-to-handle-errors-in-javascript-promises-6de92bce3afc

2020-07-20 22:40 UTC, samanthakem commented on client/pages/admin/signin.js
> +        else {
Why are you re-setting the token if the login is wrong?

2021-01-22 23:49 UTC, nathanhannig commented
I feel this can now be closed as #53 implements the same fix

2022-08-29 00:51 UTC, closed without merging